"""empty message

Revision ID: a5e7b388041b
Revises: 8632a36dc4b5
Create Date: 2022-11-18 17:49:42.408314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e7b388041b'
down_revision = '8632a36dc4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pilot_aircrafts')
    op.alter_column('aircrafts', 'hourly_rate',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('aircrafts', 'wait_time_rate',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.create_unique_constraint(None, 'aircrafts', ['aircraft_name'])
    op.drop_constraint('customers_email_key', 'customers', type_='unique')
    op.alter_column('pilots', 'hourly_rate',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('pilots', 'wait_time_rate',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pilots', 'wait_time_rate',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('pilots', 'hourly_rate',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_unique_constraint('customers_email_key', 'customers', ['email'])
    op.drop_constraint(None, 'aircrafts', type_='unique')
    op.alter_column('aircrafts', 'wait_time_rate',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('aircrafts', 'hourly_rate',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_table('pilot_aircrafts',
    sa.Column('pilot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tail_number', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.pilot_id'], name='fk_pilot_aircrafts_pilots'),
    sa.ForeignKeyConstraint(['tail_number'], ['aircrafts.tail_number'], name='fk_pilot_aircrafts_aircrafts'),
    sa.PrimaryKeyConstraint('pilot_id', 'tail_number', name='pilot_aircrafts_pkey')
    )
    # ### end Alembic commands ###
